### ISSUE TITLE
Titan Framework Error: Option type or extended class select-googlefont does not exist.

### ISSUE THREAD

**Issue by schiavassa** [gambitph/Titan-Framework-Demo-Theme#2]
Hi there,

When I try to Activate or Live Preview the Titan Demo theme I get the following error multiple times:

```
Titan Framework Error: Option type or extended class select-googlefont does not exist.
```

The Titan Framework plugin is installed and activated. I'm testing the framework on a multisite install, if that helps.

Thanks!

**Comment by bfintal** [comment]
Hi, yea we removed the option `select-googlefont` and replaced it with `font` instead. Sorry, the demo is quite outdated, don't use it :) Try using the theme generator in http://www.titanframework.net

**Comment by bfintal** [comment]
Just adjusted the readme to reflect this

**Comment by schiavassa** [comment]
Thanks, I'll do that. Looking forwards to try this out. Cheers!
